### ISSUE TITLE
iOS Project 

### ISSUE THREAD

**Issue by gvzq** [gvzq/iOS-Univeristy-Project#1]
Please review wireframes. /cc @codepathreview

**Comment by minhchau273** [comment]
#### Milestone 1
  
:+1: Great to see your GitHub repository setup and user stories defined! The user stories are a key piece of the group project. They help you prioritize the most important parts of the app to build. It's particularly important that you've split the user stories into "Required" and "Optional" stories so your team can focus on the most important aspects of the app first and then add in the optionals as time permits toward the end of the project. Please split your features into "Required" and "Optional" :smile:

Actually I don't know what purpose of your app is :confused: Can you explain more detailed?

Next week we'll move on to the next step of the group project by doing something called wireframing, which is creating a blueprint for the app.

**Comment by minhchau273** [comment]
**Note**: Please create an organization for your team and push your project there.

**Comment by minhchau273** [comment]
#### Milestone 2
  
:+1: Nice job on the wireframes! Wireframing is a common practice when building apps as it lets you create a blueprint for the app before writing any code. Having a really good blueprint that you can refer to throughout the rest of the project is a really valuable resource and will make it much easier to split up work across your team.

Could you please polish your wireframes. They're very cursory :disappointed: 

With the wireframes in hand, you should have a good idea of what your app will look like when you finish the project. Next week we'll jump into the data schema.

**Comment by npat1126** [comment]
You can view the more detailed wireframes at our repository, @minhchau273 along with more focused user stories and optionals. Thanks.

**Comment by minhchau273** [comment]
It looks clearer now. I really enjoy your idea :+1: But the wireframe still too small to see. Hope I will make sense when viewing the walk through.

You have 2 repositories, so which one do I will review the milestones in the future? Please create an issue for each milestone.

Thanks.

**Comment by gvzq** [comment]
Thank you @minhchau273. This disregard this repository. Any future commits will be at https://github.com/Bookify/Bookify
